subman:
  replicaCount: 0
  image:
    tag: v1.19.0
  rollout:
    enabled: true
  ingress:
    host: subman.dev.emzien.click
    tls:
      enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: letsencrypt-prod
