name: Package & Push Helmchart

on:
  push:
    tags:
      - "chart-v[0-9]*"

jobs:
  package-and-push-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::261175718795:role/github-actions
          aws-region: eu-central-1

      - name: Login to ECR (Helm OCI)
        run: |
          aws ecr get-login-password | helm registry login \
            --username AWS \
            --password-stdin 261175718795.dkr.ecr.eu-central-1.amazonaws.com

      - name: Lint Helm chart
        run: helm lint chart/

      - name: Build dependencies
        run: helm dependency update chart/

      - name: Package chart
        run: helm package chart/

      - name: Push Helm chart
        run: |
          helm push subman-*.tgz oci://261175718795.dkr.ecr.eu-central-1.amazonaws.com
